# Generated by Django 4.2.6 on 2023-10-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoricalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city_id", models.PositiveIntegerField()),
                ("city_name", models.CharField(max_length=255)),
                ("findname", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=2)),
                ("lon", models.FloatField()),
                ("lat", models.FloatField()),
                ("time", models.DateTimeField()),
                ("temp", models.FloatField()),
                ("pressure", models.PositiveIntegerField()),
                ("humidity", models.PositiveIntegerField()),
                ("temp_min", models.FloatField()),
                ("temp_max", models.FloatField()),
                ("wind_speed", models.FloatField()),
                ("clouds_all", models.PositiveIntegerField()),
                ("weather_id", models.PositiveIntegerField()),
                ("weather_main", models.CharField(max_length=255)),
                ("weather_description", models.CharField(max_length=255)),
                ("weather_icon", models.CharField(max_length=10)),
            ],
        ),
    ]
